#CONFIGURATION SPRING
server:
  port: 8081

management:
  server:
    port: 8091

#Configuration propre DNC
dnc:
  apiKeys:
    demarche-ms:  "70cab50d-b66e-4d47-9e10-6d6f27bf09e8"
    partenaires-ms: "ed1387ce-dec6-4112-b3ef-83d604ce5e02"
    situation-usager-ms: "51d0e4d9-cd1c-4471-9796-c5df32fc2ac7"
  front:
    # URLs du Front pour autoriser les CORS
    urls: http://dnc-dev.cloudapps.dfp.ovh,http://dnc.cloudapps.dfp.ovh,https://dnc-dev.cloudapps.dfp.ovh,https://dnc.cloudapps.dfp.ovh,http://localhost:8080,http://localhost:8090
    callbackUrl: "http://localhost:8080/login-callback"
  session:
    timeToLive: 450

#CONFIGURATION BASES
#Ces configurations sont comprises directement par Spring (Spring Appendix)
spring:
  data:
    redis:
      repositories:
        enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

#CONFIGURATION LOG
logging:
  config: classpath:log4j2.xml
  level:
    root: ERROR
    org.springframework: ERROR
    fr.gouv: INFO
    fr.gouv.modernisation.dinum.dnc.common.filter: DEBUG


##TODO
#URL de base d'accès à FranceConnect
api:
  franceconnect:
    baseUrl: "https://fcp.integ01.dev-franceconnect.fr"
    #baseUrl: "http://localhost:8181"
    cliendId: "7e067f6522a5e6178adf0a44441a9c5dc420d1e21d497397fde953ec1cffcdf6"
    clientSecret: "83f60d9e0b32b3d5782eb602735087d3c269ae7edc1352fe6076afb572834f63"
  #Configurations pour accès au service FranceConnect-MS (gestion des sessions)
  dnc:
    franceconnect-ms:
      url: "http://localhost:8081"

