#CONFIGURATION SPRING
server:
  port: 8082

management:
  server:
    port: 8092

#CONFIGURATION DNC
dnc:
  secret: "06hln6cg0cj5bpnbff190xxw4oinnwmc53y0"

#CONFIGURATION BASES
spring:
  datasource:
    initialization-mode: always
    generate-unique-name: true
    url: "jdbc:postgresql://localhost:9432/postgres"
    username: postgres
    password: dnc2020
    platform: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: false
      jmx-enabled: false
      max-active: 100
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

#CONFIGURATION LOG
logging:
  config: target/classes/log4j2.xml
  level:
    root: ERROR
    org.springframework: ERROR
    fr.gouv: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.jdbc.core.JdbcTemplate: WARN
    org.springframework.jdbc.core.StatementCreatorUtils: WARN

#Configurations pour accès au service FranceConnect-MS (gestion des sessions)
api:
  dnc:
    franceconnect-ms:
      url: "http://localhost:8081"

