#CONFIGURATION SPRING
server:
  port: 8084

management:
  server:
    port: 8094

#Configuration propre au DNC
#Configuration du time to live
dnc:
  front:
    # URLs du Front pour autoriser les CORS
    urls: http://localhost:8080,http://localhost:8090
    url: "http://localhost:8080"
    queryVerificationUrl: "/verif-justificatif?data="
  justificatif:
    nbrMoisValidite: 3
  situationUsager:
    timeToLive: 900
  demarcheUsager:
    timeToLive: 900
  ## Clé de chiffrement du DNC
  secret: 4121596A38940175
  #Pool des threads pour les appels aux API Franceconnectées
  pool:
    corePoolSize: 8
    maxPoolSize: 28
    threadNamePrefix: "SituationUsager-ApiFC-"

#Configurations des services
api:
  #Configurations pour accès aux APIs fournisseurs de données
  cnaf:
    baseUrl: "https://particulier-test.api.gouv.fr/api"
    apiKey: "3841b13fa8032ed3c31d160d3437a76a"
  dgfip:
    baseUrl: "https://particulier-test.api.gouv.fr/api"
    apiKey: "83c68bf0b6013c4daf3f8213f7212aa5"
  cnam:
    baseUrl: "https://partenaires.api.ameli.fr/test/v1/droits/beneficiaires"
    apiKey: "75dc9f1a-1b32-4b24-a84b-267d9a6e43a3"
  #Configurations pour accès au service FranceConnect-MS (gestion des sessions)
  dnc:
    franceconnect-ms:
      url: "http://localhost:8081"
      apiKey: "51d0e4d9-cd1c-4471-9796-c5df32fc2ac7"
    partenaire-ms:
      url: "http://localhost:8082"
      apiKey: "7da6941e-0021-4ddf-a7e8-7e137639e87b"


#CONFIGURATION BASES
#Ces configurations sont comprises directement par Spring (Spring Appendix)
spring:
  data:
    redis:
      repositories:
        enabled: true
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: false
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
  # ActiveMQ Configuration
  activemq:
    broker-url: tcp://localhost:61616
    user: sender
    password: sender
    non-blocking-redelivery: true
    packages:
      trust-all: false
      trusted: fr.gouv.modernisation.dinum.dnc
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      create-connection-on-startup: true
      enabled: false
      expiry-timeout: 0
      idle-timeout: 30000
      max-connections: 1
      maximum-active-session-per-connection: 500
      reconnect-on-exception: true
      time-between-expiration-check: -1
      use-anonymous-producers: true

#CONFIGURATION LOG
logging:
  config: target/classes/log4j2.xml
  level:
    root: INFO
    org.springframework: INFO
    fr.gouv: INFO


