openapi: 3.0.0

info:
  title: France Connect MS
  description: |
    Le microservice France Connect MS permet de récupérer le jeton d'accès France Connect auprès des serveurs France Connect via le code d'authorisation fourni par le front-office. Il stocke temporairement les jetons France Connect pour qu'ils servent de jeton de session entre le front-office et le back-office DNC.
    Variante du contrat d'interface pour les échanges internes au DNC.
  version: "1.0.0"


tags:
  - name: User Session
    description: Gestion de la session de l'utilisateur


paths:
  /fc/user-session/{idSession}:
    get:
      tags:
        - User Session
      description: Vérifie la validité du jeton de session et réinitialise son expiration. Cet endpoint est appelé uniquement par les microservices internes du back-office.
      operationId: checkSession
      security:
        - api_key: []
      parameters:
        - name: idSession
          in: path
          description: Identifiant de la session
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Session existante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionUsager'
        '498':
          description: Session expirée
        '400':
          description: Bad request
        '401':
          description: Session token is missing or invalid
        '403':
          description: Forbidden access
        '404':
          description: Session inexistante
        '500':
          description: Erreur du serveur
    delete:
      tags:
        - User Session
      description: Suppression de la session de l'usager. Cet endpoint est appelé uniquement par les microservices internes du back-office.
      operationId: deleteSession
      security:
        - api_key: []
      parameters:
        - name: idSession
          in: path
          description: Identifiant de la session
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
        '401':
          description: Session token is missing or invalid
        '403':
          description: Forbidden access
        '404':
          description: Resource not found
        '405':
          description: Method not allowed

components:
  schemas:
    SessionUsager:
      type: object
      description: Session d'un usager dans le système DNC
      properties:
        user_id:
          description: Identifiant de l'usager au niveau du Système DNC, dépend de l'identité Pivot.
          type: string
        idSession:
          description: Identifiant de la session au niveau du sytème DNC
          type: string
        currentToken:
          description: Token en cours d'utilisation pour la session
          type: string
        idToken:
          description: ID Tokenv côté FranceConnect
          type: string
        scopes:
          description: Liste des scopes séparées par des points-virgules
          type: string
        identitePivot:
          $ref: '#/components/schemas/IdentitePivot'
    IdentitePivot:
      title: Root Type for IdentitePivot
      description: Identité Pivot d'un utilisateur France Connect.
      type: object
      properties:
        sub:
          description: Identifiant de l'identité pivot dans France Connect.
          type: string
        given_name:
          description: Prénoms de l'utilisateur séparés par des espaces.
          type: string
        family_name:
          description: Nom de famille de l'utilisateur.
          type: string
        birthdate:
          format: date
          description: Date de naissance de l'utilisateur.
          type: string
        gender:
          description: Genre de l'utilisateur.
          type: string
        birthplace:
          description: Ville de naissance de l'utilisateur.
          type: string
        birthcountry:
          description: Pays de naissance de l'utilisateur.
          type: string
        preferred_username:
          description: Non renseigné dans le cadre de France Connect.
          type: string
        phone_number:
          description: Numéro de téléphone de l'utilisateur.
          type: string
        email:
          description: Email vérifié de l'utilisateur.
          type: string
        address:
          $ref: '#/components/schemas/Adresse'
    Adresse:
      type: object
      properties:
        country:
          type: string
        formatted:
          type: string
        locality:
          type: string
        postal_code:
          type: string
        street_address:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-Key
      in: header