spring.application.name: configserver
server.port: 8888
spring.profiles.active: native
#Par défaut, Spring ira chercher les configuration dans le répertoire ./config
#spring.cloud.config.server.native.search-locations: "file:/central-config"

logging:
  level:
    root: INFO
    org.springframework.cloud.config: INFO