openapi: 3.0.0
info:
  title: API pour les métadonnées autour des démarches
  description: API pour les métadonnées autour des démarches
  version: 1.0.0

paths:
  /meta/demarche/scopes:
    get:
      description: Renvoie la liste des scopes associés à une démarche.
      operationId: getScopesFranceconnectFromDemarcheCode
      parameters:
        - name: codeDemarche
          description: Code de la démarche
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/DemarcheEnum'

      responses:
        200:
          description: Liste des scopes concernées
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: Le code de démarche n'est pas reconnu par le système DNC
        500:
          description: Le code de démarche n'est pas encore géré par le système DNC
  /meta/demarche/etapes/{idDemarche}:
    get:
      description: Permet d'obtenir le nombre d'étape de la saisie d'une démarche. Ne peut être appeler qu'après avoir récupérer les données de la démarche une 1ere fois.
      security:
        - DncSessionIdInHeaderAuth: []
      operationId: getEtapesForDemarches
      parameters:
        - name: idDemarche
          in: path
          description: Identifiant de la démarche en base
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Les données brutes correspondantes pour la démarche et l'usager sont renvoyées.
          content:
            application/json:
              schema:
                description: Liste des étape de la démarche pour l'usager
                type: array
                items:
                  $ref: '#/components/schemas/Etape'
        404:
          description: Le code de démarche n'est pas reconnu par le système DNC
        500:
          description: Le code de démarche n'est pas encore géré par le système DNC

  /embedded/data/{codeDemarche}:
    post:
      security:
        - DncSessionIdInHeaderAuth: []
      operationId: fetchDataForDemarche
      parameters:
        - name: codeDemarche
          in: path
          description: Code de la démarche
          required: true
          schema:
            $ref: '#/components/schemas/DemarcheEnum'
      requestBody:
        required: true
        description: Données et identifiants supplémentaires nécessaires pour récupérer les données de la démarche
        content:
          application/json:
            schema:
              description: Map des Données et identifiants supplémentaires pour la récupération des données de la démarche
              type: object
              additionalProperties:
                type: string
      responses:
        200:
          description: Les données brutes correspondantes pour la démarche et l'usager sont renvoyées.
          content:
            application/json:
              schema:
                description: Map des données brutes pour une saisie de la démarches, contient l'identifiant de la démarche pour l'usager.
                type: object
                additionalProperties:
                  type: string
        404:
          description: Le code de démarche n'est pas reconnu par le système DNC
        500:
          description: Le code de démarche n'est pas encore géré par le système DNC
  /embedded/demarche/{idDemarche}:
    put:
      security:
        - DncSessionIdInHeaderAuth: []
      operationId: updateDemarche
      description: Mets à jour les données de la démarche stockée en base. La démarche peut être mise à jour autant que fois que nécessaires.
      parameters:
        - name: idDemarche
          in: path
          description: Identifiant de la démarche en base
          schema:
            type: string
            format: uuid
          required: true
        - name: etape
          in: query
          description: Etape du traitement de la démarche.
          schema:
            type: integer
      requestBody:
        required: true
        description: Données de la démarche à sauvegarder.
        content:
          application/json:
            schema:
              description: Map des données de la démarches
              type: object
              additionalProperties:
                type: string
      responses:
        200:
          description: La démarche est finalisée dans le DNC et peut être récupérer par le Fournisseur de Service.
          content:
            application/json:
              schema:
                description: Map des données de la démarches
                type: object
                additionalProperties:
                  type: string
        404:
          description: Le code de démarche n'est pas reconnu par le système DNC
        500:
          description: Le code de démarche n'est pas encore géré par le système DNC
    post:
      security:
        - DncSessionIdInHeaderAuth: []
      operationId: finalizeDemarche
      description: Finalise la démarche et bloque les mises à jour. Les données de la démarches seront transformées pour récupération par le Fournisseur de service. Le justificatif est générée à ce moment.
      parameters:
        - name: idDemarche
          in: path
          description: Identifiant de la démarche en base
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        description: Données de la démarche à sauvegarder.
        content:
          application/json:
            schema:
              description: Map des données de la démarches
              type: object
              additionalProperties:
                type: string
      responses:
        200:
          description: La démarche est initialisée dans le DNC avec les données sélectionnées.
          content:
            application/json:
              schema:
                description: Identifiant des données de la démarches
                type: string
                format: uuid
        404:
          description: Le code de démarche n'est pas reconnu par le système DNC
        500:
          description: Le code de démarche n'est pas encore géré par le système DNC

  /embedded/justificatif/{idDemarche}:
    get:
      security:
        - DncSessionIdInHeaderAuth: []
      operationId: getJustificatifForDemarche
      description: Renvoie le justificatif de la démarche stockée en base.
      parameters:
        - name: idDemarche
          in: path
          description: Identifiant de la démarche en base
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Le justificatif associée à la démarche
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Justificatif'
        404:
          description: L'identifiant de démarche est inconnu par le système DNC
        500:
          description: Une erreur est survenue lors de la récupération du Justificatif


components:
  securitySchemes:
    # Précise que le Header de la session de l'Usager doit être présent pour appeler cette API
    DncSessionIdInHeaderAuth:
      type: apiKey
      in: header
      name: DNC-ID-SESSION
  schemas:
    DemarcheEnum:
      description: Enum des démarches gérées par le système DNC
      example: CARTE_STATIONNEMENT
      type: string
      enum:
        - CARTE_STATIONNEMENT
        - RESTAURATION_SCOLAIRE
        - DEMANDE_AIDE_PONCTUELLE
        - TABLEAU_DE_BORD
      x-enum-elements:
        - name: CARTE_STATIONNEMENT
          description: Demande de carte de stationnement
        - name: RESTAURATION_SCOLAIRE
          description: Inscription à la restauration scolaire
        - name: DEMANDE_AIDE_PONCTUELLE
          description: Demande d'aide financiaire ponctuelle liée à un enfant inscrit dans le secondaire
    Justificatif:
      type: object
      properties:
        id:
          type: string
          description: 'Identifiant unique du justificatif'
        filename:
          type: string
          description: 'Nom du justificatif'
        libelle:
          type: string
          description: 'Libellé du justificatif'
        size:
          type: string
          description: 'Taille du justificatif'
        filetype:
          type: string
          description: 'Type du Justificatif'
        idPartenaire:
          type: string
          description: 'Identifiant du partenaire associé à ce justificatif'
        contenu:
          type: string
          format: byte
          description: 'Contenu du Justificatif encodé en base64, uniquement si les données du document sont demandées.'
    Etape:
      type: object
      properties:
        name:
          type: string
          description: "Nom de l'étape"
        type:
          type: string
          description: "Type de l'étape : saisieDonneesComplementaire, selection, récapitulatif, justificatif"
        champsSelectionnes:
          type: string
          description: "Liste des champs à remplir pour la ou les sélections par l'usager"
        sourceListe:
          type: string
          description: "Source des listes de sélection danns les données brutes"
    MetaDonnees:
      type: object
      properties:
        name:
          type: string
          description: 'Nom de la données'
        type:
          type: string
          description: 'Type de la donnée parmi String (défaut), Date, Liste, Objet, ListeObjets'
        formatDate:
          type: string
          description: 'Le format de la date si la donnée est de type Date'
        description:
          type: string
          description: 'Description du champ'